name: Python CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  build:
    runs-on: windows-latest  # Run the job on a Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test_app.py

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Deploy to Server (example)
        run: |
          echo "Deploying application to server..."  # Add your deployment commands here
          # Example: scp or rsync to copy files to your server

