name: Python CI/CD Pipeline

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main  # You can replace this with your default branch if different

# Define the jobs
jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the environment to run the job on

    # Steps that the job will execute
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.8'  # Specify the Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          python -m unittest test_app.py  # Run the tests in test_app.py

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job will only run after the 'build' job has completed successfully

    # Deploy steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server (example)
        run: |
          echo "Deploying application to server..."  # Add your deployment commands here
          # Example: scp or rsync to copy files to your server

